wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1694418130.377584
    t:
      1:
      - 1
      - 55
      3:
      - 23
      4: 3.10.9
      5: 0.15.8
      8:
      - 3
      - 5
